### ISSUE TITLE
Recursion issue Python 3.6

### ISSUE THREAD

**Issue by xnomagichash** [Sentenai/py-sentenai#3]
Here's the details: https://github.com/gevent/gevent/issues/903

We should catch and/or document this.

gevent 1.2 is necessary in python 3.6

**Comment by selik** [comment]
I've upgraded and it seems to work most of the time, but I still occasionally get the recursion error.

```
Traceback (most recent call last):
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "mm/collect.py", line 103, in push
    timestamp=timestamp)
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/sentenai/__init__.py", line 798, in put
    resp = requests.post(url, json=jd, headers=headers)
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 265, in create_urllib3_context
    context.options |= options
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Users/mike/miniconda/envs/sci/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 319 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by xnomagichash** [comment]
gevent is now removed from the library to avoid these issues in the future.
