### ISSUE TITLE
instantiating Sentenai object causes a hang

### ISSUE THREAD

**Issue by nicklawls** [sentenai/py-sentenai#86]
```python
# example.py
from sentenai import *

sentenai = Sentenai('15b15681ffd0a97d55f87129f32754a1', 'http://localhost:8000')
```
running this hangs indefinitely

`> python example.py` 

Killing it with `Ctrl-C` gives this stack trace

```
Exception ignored in: <module 'threading' from '/Users/xilnocas/.pyenv/versions/3.6.1/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/Users/xilnocas/.pyenv/versions/3.6.1/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/Users/xilnocas/.pyenv/versions/3.6.1/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/Users/xilnocas/.pyenv/versions/3.6.1/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by xilnocas** [comment]
This is on python 3.6.1, sentenai 99.1.1
